version: '3'
services:
  n01rcu:
    container_name: n01rcu-prod
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - APP_PORT=3001
      - NODE_ENV=production
    ports:
      - '3000:3000'
      - '3001:3001'
