version: '3'
services:
  app:
    container_name: n01rcu-app-dev
    build:
      context: ./app
      dockerfile: Dockerfile
    stdin_open: true
    environment:
      - PORT=7000
      - NODE_ENV=development
    ports:
      - '7000:7000'
    volumes:
      - './app:/app:cached'
  server:
    container_name: n01rcu-server-dev
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=7001
      - APP_PORT=7005
      - NODE_ENV=development
    ports:
      - '7001:7001'
      - '7005:7005'
    volumes:
      - './server:/server:cached'
