version: '3'
services:
  n01rcu_app:
    stdin_open: true
    build:
      context: ./app
      dockerfile: 'Dockerfile'
    ports:
      - '7001:7001'
    volumes:
        - './app:/app:cached'
  n01rcu_server:
    build:
      context: ./server
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    volumes:
      - './server:/server:cached'
